<?php

namespace Kaiwh\Geo\Seeds;

use Illuminate\Database\Seeder;

class GeoCityTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('geo_cities')->delete();

        \DB::table('geo_cities')->insert(array(
            0   => array(
                'id'          => 1,
                'province_id' => 2,
                'name'        => '北京',
                'status'      => 1,
            ),
            1   => array(
                'id'          => 2,
                'province_id' => 3,
                'name'        => '安庆',
                'status'      => 1,
            ),
            2   => array(
                'id'          => 3,
                'province_id' => 3,
                'name'        => '蚌埠',
                'status'      => 1,
            ),
            3   => array(
                'id'          => 4,
                'province_id' => 3,
                'name'        => '巢湖',
                'status'      => 1,
            ),
            4   => array(
                'id'          => 5,
                'province_id' => 3,
                'name'        => '池州',
                'status'      => 1,
            ),
            5   => array(
                'id'          => 6,
                'province_id' => 3,
                'name'        => '滁州',
                'status'      => 1,
            ),
            6   => array(
                'id'          => 7,
                'province_id' => 3,
                'name'        => '阜阳',
                'status'      => 1,
            ),
            7   => array(
                'id'          => 8,
                'province_id' => 3,
                'name'        => '淮北',
                'status'      => 1,
            ),
            8   => array(
                'id'          => 9,
                'province_id' => 3,
                'name'        => '淮南',
                'status'      => 1,
            ),
            9   => array(
                'id'          => 10,
                'province_id' => 3,
                'name'        => '黄山',
                'status'      => 1,
            ),
            10  => array(
                'id'          => 11,
                'province_id' => 3,
                'name'        => '六安',
                'status'      => 1,
            ),
            11  => array(
                'id'          => 12,
                'province_id' => 3,
                'name'        => '马鞍山',
                'status'      => 1,
            ),
            12  => array(
                'id'          => 13,
                'province_id' => 3,
                'name'        => '宿州',
                'status'      => 1,
            ),
            13  => array(
                'id'          => 14,
                'province_id' => 3,
                'name'        => '铜陵',
                'status'      => 1,
            ),
            14  => array(
                'id'          => 15,
                'province_id' => 3,
                'name'        => '芜湖',
                'status'      => 1,
            ),
            15  => array(
                'id'          => 16,
                'province_id' => 3,
                'name'        => '宣城',
                'status'      => 1,
            ),
            16  => array(
                'id'          => 17,
                'province_id' => 3,
                'name'        => '亳州',
                'status'      => 1,
            ),
            17  => array(
                'id'          => 18,
                'province_id' => 3,
                'name'        => '合肥',
                'status'      => 1,
            ),
            18  => array(
                'id'          => 19,
                'province_id' => 4,
                'name'        => '福州',
                'status'      => 1,
            ),
            19  => array(
                'id'          => 20,
                'province_id' => 4,
                'name'        => '龙岩',
                'status'      => 1,
            ),
            20  => array(
                'id'          => 21,
                'province_id' => 4,
                'name'        => '南平',
                'status'      => 1,
            ),
            21  => array(
                'id'          => 22,
                'province_id' => 4,
                'name'        => '宁德',
                'status'      => 1,
            ),
            22  => array(
                'id'          => 23,
                'province_id' => 4,
                'name'        => '莆田',
                'status'      => 1,
            ),
            23  => array(
                'id'          => 24,
                'province_id' => 4,
                'name'        => '泉州',
                'status'      => 1,
            ),
            24  => array(
                'id'          => 25,
                'province_id' => 4,
                'name'        => '三明',
                'status'      => 1,
            ),
            25  => array(
                'id'          => 26,
                'province_id' => 4,
                'name'        => '厦门',
                'status'      => 1,
            ),
            26  => array(
                'id'          => 27,
                'province_id' => 4,
                'name'        => '漳州',
                'status'      => 1,
            ),
            27  => array(
                'id'          => 28,
                'province_id' => 5,
                'name'        => '兰州',
                'status'      => 1,
            ),
            28  => array(
                'id'          => 29,
                'province_id' => 5,
                'name'        => '白银',
                'status'      => 1,
            ),
            29  => array(
                'id'          => 30,
                'province_id' => 5,
                'name'        => '定西',
                'status'      => 1,
            ),
            30  => array(
                'id'          => 31,
                'province_id' => 5,
                'name'        => '甘南',
                'status'      => 1,
            ),
            31  => array(
                'id'          => 32,
                'province_id' => 5,
                'name'        => '嘉峪关',
                'status'      => 1,
            ),
            32  => array(
                'id'          => 33,
                'province_id' => 5,
                'name'        => '金昌',
                'status'      => 1,
            ),
            33  => array(
                'id'          => 34,
                'province_id' => 5,
                'name'        => '酒泉',
                'status'      => 1,
            ),
            34  => array(
                'id'          => 35,
                'province_id' => 5,
                'name'        => '临夏',
                'status'      => 1,
            ),
            35  => array(
                'id'          => 36,
                'province_id' => 5,
                'name'        => '陇南',
                'status'      => 1,
            ),
            36  => array(
                'id'          => 37,
                'province_id' => 5,
                'name'        => '平凉',
                'status'      => 1,
            ),
            37  => array(
                'id'          => 38,
                'province_id' => 5,
                'name'        => '庆阳',
                'status'      => 1,
            ),
            38  => array(
                'id'          => 39,
                'province_id' => 5,
                'name'        => '天水',
                'status'      => 1,
            ),
            39  => array(
                'id'          => 40,
                'province_id' => 5,
                'name'        => '武威',
                'status'      => 1,
            ),
            40  => array(
                'id'          => 41,
                'province_id' => 5,
                'name'        => '张掖',
                'status'      => 1,
            ),
            41  => array(
                'id'          => 42,
                'province_id' => 6,
                'name'        => '广州',
                'status'      => 1,
            ),
            42  => array(
                'id'          => 43,
                'province_id' => 6,
                'name'        => '深圳',
                'status'      => 1,
            ),
            43  => array(
                'id'          => 44,
                'province_id' => 6,
                'name'        => '潮州',
                'status'      => 1,
            ),
            44  => array(
                'id'          => 45,
                'province_id' => 6,
                'name'        => '东莞',
                'status'      => 1,
            ),
            45  => array(
                'id'          => 46,
                'province_id' => 6,
                'name'        => '佛山',
                'status'      => 1,
            ),
            46  => array(
                'id'          => 47,
                'province_id' => 6,
                'name'        => '河源',
                'status'      => 1,
            ),
            47  => array(
                'id'          => 48,
                'province_id' => 6,
                'name'        => '惠州',
                'status'      => 1,
            ),
            48  => array(
                'id'          => 49,
                'province_id' => 6,
                'name'        => '江门',
                'status'      => 1,
            ),
            49  => array(
                'id'          => 50,
                'province_id' => 6,
                'name'        => '揭阳',
                'status'      => 1,
            ),
            50  => array(
                'id'          => 51,
                'province_id' => 6,
                'name'        => '茂名',
                'status'      => 1,
            ),
            51  => array(
                'id'          => 52,
                'province_id' => 6,
                'name'        => '梅州',
                'status'      => 1,
            ),
            52  => array(
                'id'          => 53,
                'province_id' => 6,
                'name'        => '清远',
                'status'      => 1,
            ),
            53  => array(
                'id'          => 54,
                'province_id' => 6,
                'name'        => '汕头',
                'status'      => 1,
            ),
            54  => array(
                'id'          => 55,
                'province_id' => 6,
                'name'        => '汕尾',
                'status'      => 1,
            ),
            55  => array(
                'id'          => 56,
                'province_id' => 6,
                'name'        => '韶关',
                'status'      => 1,
            ),
            56  => array(
                'id'          => 57,
                'province_id' => 6,
                'name'        => '阳江',
                'status'      => 1,
            ),
            57  => array(
                'id'          => 58,
                'province_id' => 6,
                'name'        => '云浮',
                'status'      => 1,
            ),
            58  => array(
                'id'          => 59,
                'province_id' => 6,
                'name'        => '湛江',
                'status'      => 1,
            ),
            59  => array(
                'id'          => 60,
                'province_id' => 6,
                'name'        => '肇庆',
                'status'      => 1,
            ),
            60  => array(
                'id'          => 61,
                'province_id' => 6,
                'name'        => '中山',
                'status'      => 1,
            ),
            61  => array(
                'id'          => 62,
                'province_id' => 6,
                'name'        => '珠海',
                'status'      => 1,
            ),
            62  => array(
                'id'          => 63,
                'province_id' => 7,
                'name'        => '南宁',
                'status'      => 1,
            ),
            63  => array(
                'id'          => 64,
                'province_id' => 7,
                'name'        => '桂林',
                'status'      => 1,
            ),
            64  => array(
                'id'          => 65,
                'province_id' => 7,
                'name'        => '百色',
                'status'      => 1,
            ),
            65  => array(
                'id'          => 66,
                'province_id' => 7,
                'name'        => '北海',
                'status'      => 1,
            ),
            66  => array(
                'id'          => 67,
                'province_id' => 7,
                'name'        => '崇左',
                'status'      => 1,
            ),
            67  => array(
                'id'          => 68,
                'province_id' => 7,
                'name'        => '防城港',
                'status'      => 1,
            ),
            68  => array(
                'id'          => 69,
                'province_id' => 7,
                'name'        => '贵港',
                'status'      => 1,
            ),
            69  => array(
                'id'          => 70,
                'province_id' => 7,
                'name'        => '河池',
                'status'      => 1,
            ),
            70  => array(
                'id'          => 71,
                'province_id' => 7,
                'name'        => '贺州',
                'status'      => 1,
            ),
            71  => array(
                'id'          => 72,
                'province_id' => 7,
                'name'        => '来宾',
                'status'      => 1,
            ),
            72  => array(
                'id'          => 73,
                'province_id' => 7,
                'name'        => '柳州',
                'status'      => 1,
            ),
            73  => array(
                'id'          => 74,
                'province_id' => 7,
                'name'        => '钦州',
                'status'      => 1,
            ),
            74  => array(
                'id'          => 75,
                'province_id' => 7,
                'name'        => '梧州',
                'status'      => 1,
            ),
            75  => array(
                'id'          => 76,
                'province_id' => 7,
                'name'        => '玉林',
                'status'      => 1,
            ),
            76  => array(
                'id'          => 77,
                'province_id' => 8,
                'name'        => '贵阳',
                'status'      => 1,
            ),
            77  => array(
                'id'          => 78,
                'province_id' => 8,
                'name'        => '安顺',
                'status'      => 1,
            ),
            78  => array(
                'id'          => 79,
                'province_id' => 8,
                'name'        => '毕节',
                'status'      => 1,
            ),
            79  => array(
                'id'          => 80,
                'province_id' => 8,
                'name'        => '六盘水',
                'status'      => 1,
            ),
            80  => array(
                'id'          => 81,
                'province_id' => 8,
                'name'        => '黔东南',
                'status'      => 1,
            ),
            81  => array(
                'id'          => 82,
                'province_id' => 8,
                'name'        => '黔南',
                'status'      => 1,
            ),
            82  => array(
                'id'          => 83,
                'province_id' => 8,
                'name'        => '黔西南',
                'status'      => 1,
            ),
            83  => array(
                'id'          => 84,
                'province_id' => 8,
                'name'        => '铜仁',
                'status'      => 1,
            ),
            84  => array(
                'id'          => 85,
                'province_id' => 8,
                'name'        => '遵义',
                'status'      => 1,
            ),
            85  => array(
                'id'          => 86,
                'province_id' => 9,
                'name'        => '海口',
                'status'      => 1,
            ),
            86  => array(
                'id'          => 87,
                'province_id' => 9,
                'name'        => '三亚',
                'status'      => 1,
            ),
            87  => array(
                'id'          => 88,
                'province_id' => 9,
                'name'        => '白沙',
                'status'      => 1,
            ),
            88  => array(
                'id'          => 89,
                'province_id' => 9,
                'name'        => '保亭',
                'status'      => 1,
            ),
            89  => array(
                'id'          => 90,
                'province_id' => 9,
                'name'        => '昌江',
                'status'      => 1,
            ),
            90  => array(
                'id'          => 91,
                'province_id' => 9,
                'name'        => '澄迈县',
                'status'      => 1,
            ),
            91  => array(
                'id'          => 92,
                'province_id' => 9,
                'name'        => '定安县',
                'status'      => 1,
            ),
            92  => array(
                'id'          => 93,
                'province_id' => 9,
                'name'        => '东方',
                'status'      => 1,
            ),
            93  => array(
                'id'          => 94,
                'province_id' => 9,
                'name'        => '乐东',
                'status'      => 1,
            ),
            94  => array(
                'id'          => 95,
                'province_id' => 9,
                'name'        => '临高县',
                'status'      => 1,
            ),
            95  => array(
                'id'          => 96,
                'province_id' => 9,
                'name'        => '陵水',
                'status'      => 1,
            ),
            96  => array(
                'id'          => 97,
                'province_id' => 9,
                'name'        => '琼海',
                'status'      => 1,
            ),
            97  => array(
                'id'          => 98,
                'province_id' => 9,
                'name'        => '琼中',
                'status'      => 1,
            ),
            98  => array(
                'id'          => 99,
                'province_id' => 9,
                'name'        => '屯昌县',
                'status'      => 1,
            ),
            99  => array(
                'id'          => 100,
                'province_id' => 9,
                'name'        => '万宁',
                'status'      => 1,
            ),
            100 => array(
                'id'          => 101,
                'province_id' => 9,
                'name'        => '文昌',
                'status'      => 1,
            ),
            101 => array(
                'id'          => 102,
                'province_id' => 9,
                'name'        => '五指山',
                'status'      => 1,
            ),
            102 => array(
                'id'          => 103,
                'province_id' => 9,
                'name'        => '儋州',
                'status'      => 1,
            ),
            103 => array(
                'id'          => 104,
                'province_id' => 10,
                'name'        => '石家庄',
                'status'      => 1,
            ),
            104 => array(
                'id'          => 105,
                'province_id' => 10,
                'name'        => '保定',
                'status'      => 1,
            ),
            105 => array(
                'id'          => 106,
                'province_id' => 10,
                'name'        => '沧州',
                'status'      => 1,
            ),
            106 => array(
                'id'          => 107,
                'province_id' => 10,
                'name'        => '承德',
                'status'      => 1,
            ),
            107 => array(
                'id'          => 108,
                'province_id' => 10,
                'name'        => '邯郸',
                'status'      => 1,
            ),
            108 => array(
                'id'          => 109,
                'province_id' => 10,
                'name'        => '衡水',
                'status'      => 1,
            ),
            109 => array(
                'id'          => 110,
                'province_id' => 10,
                'name'        => '廊坊',
                'status'      => 1,
            ),
            110 => array(
                'id'          => 111,
                'province_id' => 10,
                'name'        => '秦皇岛',
                'status'      => 1,
            ),
            111 => array(
                'id'          => 112,
                'province_id' => 10,
                'name'        => '唐山',
                'status'      => 1,
            ),
            112 => array(
                'id'          => 113,
                'province_id' => 10,
                'name'        => '邢台',
                'status'      => 1,
            ),
            113 => array(
                'id'          => 114,
                'province_id' => 10,
                'name'        => '张家口',
                'status'      => 1,
            ),
            114 => array(
                'id'          => 115,
                'province_id' => 11,
                'name'        => '郑州',
                'status'      => 1,
            ),
            115 => array(
                'id'          => 116,
                'province_id' => 11,
                'name'        => '洛阳',
                'status'      => 1,
            ),
            116 => array(
                'id'          => 117,
                'province_id' => 11,
                'name'        => '开封',
                'status'      => 1,
            ),
            117 => array(
                'id'          => 118,
                'province_id' => 11,
                'name'        => '安阳',
                'status'      => 1,
            ),
            118 => array(
                'id'          => 119,
                'province_id' => 11,
                'name'        => '鹤壁',
                'status'      => 1,
            ),
            119 => array(
                'id'          => 120,
                'province_id' => 11,
                'name'        => '济源',
                'status'      => 1,
            ),
            120 => array(
                'id'          => 121,
                'province_id' => 11,
                'name'        => '焦作',
                'status'      => 1,
            ),
            121 => array(
                'id'          => 122,
                'province_id' => 11,
                'name'        => '南阳',
                'status'      => 1,
            ),
            122 => array(
                'id'          => 123,
                'province_id' => 11,
                'name'        => '平顶山',
                'status'      => 1,
            ),
            123 => array(
                'id'          => 124,
                'province_id' => 11,
                'name'        => '三门峡',
                'status'      => 1,
            ),
            124 => array(
                'id'          => 125,
                'province_id' => 11,
                'name'        => '商丘',
                'status'      => 1,
            ),
            125 => array(
                'id'          => 126,
                'province_id' => 11,
                'name'        => '新乡',
                'status'      => 1,
            ),
            126 => array(
                'id'          => 127,
                'province_id' => 11,
                'name'        => '信阳',
                'status'      => 1,
            ),
            127 => array(
                'id'          => 128,
                'province_id' => 11,
                'name'        => '许昌',
                'status'      => 1,
            ),
            128 => array(
                'id'          => 129,
                'province_id' => 11,
                'name'        => '周口',
                'status'      => 1,
            ),
            129 => array(
                'id'          => 130,
                'province_id' => 11,
                'name'        => '驻马店',
                'status'      => 1,
            ),
            130 => array(
                'id'          => 131,
                'province_id' => 11,
                'name'        => '漯河',
                'status'      => 1,
            ),
            131 => array(
                'id'          => 132,
                'province_id' => 11,
                'name'        => '濮阳',
                'status'      => 1,
            ),
            132 => array(
                'id'          => 133,
                'province_id' => 12,
                'name'        => '哈尔滨',
                'status'      => 1,
            ),
            133 => array(
                'id'          => 134,
                'province_id' => 12,
                'name'        => '大庆',
                'status'      => 1,
            ),
            134 => array(
                'id'          => 135,
                'province_id' => 12,
                'name'        => '大兴安岭',
                'status'      => 1,
            ),
            135 => array(
                'id'          => 136,
                'province_id' => 12,
                'name'        => '鹤岗',
                'status'      => 1,
            ),
            136 => array(
                'id'          => 137,
                'province_id' => 12,
                'name'        => '黑河',
                'status'      => 1,
            ),
            137 => array(
                'id'          => 138,
                'province_id' => 12,
                'name'        => '鸡西',
                'status'      => 1,
            ),
            138 => array(
                'id'          => 139,
                'province_id' => 12,
                'name'        => '佳木斯',
                'status'      => 1,
            ),
            139 => array(
                'id'          => 140,
                'province_id' => 12,
                'name'        => '牡丹江',
                'status'      => 1,
            ),
            140 => array(
                'id'          => 141,
                'province_id' => 12,
                'name'        => '七台河',
                'status'      => 1,
            ),
            141 => array(
                'id'          => 142,
                'province_id' => 12,
                'name'        => '齐齐哈尔',
                'status'      => 1,
            ),
            142 => array(
                'id'          => 143,
                'province_id' => 12,
                'name'        => '双鸭山',
                'status'      => 1,
            ),
            143 => array(
                'id'          => 144,
                'province_id' => 12,
                'name'        => '绥化',
                'status'      => 1,
            ),
            144 => array(
                'id'          => 145,
                'province_id' => 12,
                'name'        => '伊春',
                'status'      => 1,
            ),
            145 => array(
                'id'          => 146,
                'province_id' => 13,
                'name'        => '武汉',
                'status'      => 1,
            ),
            146 => array(
                'id'          => 147,
                'province_id' => 13,
                'name'        => '仙桃',
                'status'      => 1,
            ),
            147 => array(
                'id'          => 148,
                'province_id' => 13,
                'name'        => '鄂州',
                'status'      => 1,
            ),
            148 => array(
                'id'          => 149,
                'province_id' => 13,
                'name'        => '黄冈',
                'status'      => 1,
            ),
            149 => array(
                'id'          => 150,
                'province_id' => 13,
                'name'        => '黄石',
                'status'      => 1,
            ),
            150 => array(
                'id'          => 151,
                'province_id' => 13,
                'name'        => '荆门',
                'status'      => 1,
            ),
            151 => array(
                'id'          => 152,
                'province_id' => 13,
                'name'        => '荆州',
                'status'      => 1,
            ),
            152 => array(
                'id'          => 153,
                'province_id' => 13,
                'name'        => '潜江',
                'status'      => 1,
            ),
            153 => array(
                'id'          => 154,
                'province_id' => 13,
                'name'        => '神农架林区',
                'status'      => 1,
            ),
            154 => array(
                'id'          => 155,
                'province_id' => 13,
                'name'        => '十堰',
                'status'      => 1,
            ),
            155 => array(
                'id'          => 156,
                'province_id' => 13,
                'name'        => '随州',
                'status'      => 1,
            ),
            156 => array(
                'id'          => 157,
                'province_id' => 13,
                'name'        => '天门',
                'status'      => 1,
            ),
            157 => array(
                'id'          => 158,
                'province_id' => 13,
                'name'        => '咸宁',
                'status'      => 1,
            ),
            158 => array(
                'id'          => 159,
                'province_id' => 13,
                'name'        => '襄樊',
                'status'      => 1,
            ),
            159 => array(
                'id'          => 160,
                'province_id' => 13,
                'name'        => '孝感',
                'status'      => 1,
            ),
            160 => array(
                'id'          => 161,
                'province_id' => 13,
                'name'        => '宜昌',
                'status'      => 1,
            ),
            161 => array(
                'id'          => 162,
                'province_id' => 13,
                'name'        => '恩施',
                'status'      => 1,
            ),
            162 => array(
                'id'          => 163,
                'province_id' => 14,
                'name'        => '长沙',
                'status'      => 1,
            ),
            163 => array(
                'id'          => 164,
                'province_id' => 14,
                'name'        => '张家界',
                'status'      => 1,
            ),
            164 => array(
                'id'          => 165,
                'province_id' => 14,
                'name'        => '常德',
                'status'      => 1,
            ),
            165 => array(
                'id'          => 166,
                'province_id' => 14,
                'name'        => '郴州',
                'status'      => 1,
            ),
            166 => array(
                'id'          => 167,
                'province_id' => 14,
                'name'        => '衡阳',
                'status'      => 1,
            ),
            167 => array(
                'id'          => 168,
                'province_id' => 14,
                'name'        => '怀化',
                'status'      => 1,
            ),
            168 => array(
                'id'          => 169,
                'province_id' => 14,
                'name'        => '娄底',
                'status'      => 1,
            ),
            169 => array(
                'id'          => 170,
                'province_id' => 14,
                'name'        => '邵阳',
                'status'      => 1,
            ),
            170 => array(
                'id'          => 171,
                'province_id' => 14,
                'name'        => '湘潭',
                'status'      => 1,
            ),
            171 => array(
                'id'          => 172,
                'province_id' => 14,
                'name'        => '湘西',
                'status'      => 1,
            ),
            172 => array(
                'id'          => 173,
                'province_id' => 14,
                'name'        => '益阳',
                'status'      => 1,
            ),
            173 => array(
                'id'          => 174,
                'province_id' => 14,
                'name'        => '永州',
                'status'      => 1,
            ),
            174 => array(
                'id'          => 175,
                'province_id' => 14,
                'name'        => '岳阳',
                'status'      => 1,
            ),
            175 => array(
                'id'          => 176,
                'province_id' => 14,
                'name'        => '株洲',
                'status'      => 1,
            ),
            176 => array(
                'id'          => 177,
                'province_id' => 15,
                'name'        => '长春',
                'status'      => 1,
            ),
            177 => array(
                'id'          => 178,
                'province_id' => 15,
                'name'        => '吉林',
                'status'      => 1,
            ),
            178 => array(
                'id'          => 179,
                'province_id' => 15,
                'name'        => '白城',
                'status'      => 1,
            ),
            179 => array(
                'id'          => 180,
                'province_id' => 15,
                'name'        => '白山',
                'status'      => 1,
            ),
            180 => array(
                'id'          => 181,
                'province_id' => 15,
                'name'        => '辽源',
                'status'      => 1,
            ),
            181 => array(
                'id'          => 182,
                'province_id' => 15,
                'name'        => '四平',
                'status'      => 1,
            ),
            182 => array(
                'id'          => 183,
                'province_id' => 15,
                'name'        => '松原',
                'status'      => 1,
            ),
            183 => array(
                'id'          => 184,
                'province_id' => 15,
                'name'        => '通化',
                'status'      => 1,
            ),
            184 => array(
                'id'          => 185,
                'province_id' => 15,
                'name'        => '延边',
                'status'      => 1,
            ),
            185 => array(
                'id'          => 186,
                'province_id' => 16,
                'name'        => '南京',
                'status'      => 1,
            ),
            186 => array(
                'id'          => 187,
                'province_id' => 16,
                'name'        => '苏州',
                'status'      => 1,
            ),
            187 => array(
                'id'          => 188,
                'province_id' => 16,
                'name'        => '无锡',
                'status'      => 1,
            ),
            188 => array(
                'id'          => 189,
                'province_id' => 16,
                'name'        => '常州',
                'status'      => 1,
            ),
            189 => array(
                'id'          => 190,
                'province_id' => 16,
                'name'        => '淮安',
                'status'      => 1,
            ),
            190 => array(
                'id'          => 191,
                'province_id' => 16,
                'name'        => '连云港',
                'status'      => 1,
            ),
            191 => array(
                'id'          => 192,
                'province_id' => 16,
                'name'        => '南通',
                'status'      => 1,
            ),
            192 => array(
                'id'          => 193,
                'province_id' => 16,
                'name'        => '宿迁',
                'status'      => 1,
            ),
            193 => array(
                'id'          => 194,
                'province_id' => 16,
                'name'        => '泰州',
                'status'      => 1,
            ),
            194 => array(
                'id'          => 195,
                'province_id' => 16,
                'name'        => '徐州',
                'status'      => 1,
            ),
            195 => array(
                'id'          => 196,
                'province_id' => 16,
                'name'        => '盐城',
                'status'      => 1,
            ),
            196 => array(
                'id'          => 197,
                'province_id' => 16,
                'name'        => '扬州',
                'status'      => 1,
            ),
            197 => array(
                'id'          => 198,
                'province_id' => 16,
                'name'        => '镇江',
                'status'      => 1,
            ),
            198 => array(
                'id'          => 199,
                'province_id' => 17,
                'name'        => '南昌',
                'status'      => 1,
            ),
            199 => array(
                'id'          => 200,
                'province_id' => 17,
                'name'        => '抚州',
                'status'      => 1,
            ),
            200 => array(
                'id'          => 201,
                'province_id' => 17,
                'name'        => '赣州',
                'status'      => 1,
            ),
            201 => array(
                'id'          => 202,
                'province_id' => 17,
                'name'        => '吉安',
                'status'      => 1,
            ),
            202 => array(
                'id'          => 203,
                'province_id' => 17,
                'name'        => '景德镇',
                'status'      => 1,
            ),
            203 => array(
                'id'          => 204,
                'province_id' => 17,
                'name'        => '九江',
                'status'      => 1,
            ),
            204 => array(
                'id'          => 205,
                'province_id' => 17,
                'name'        => '萍乡',
                'status'      => 1,
            ),
            205 => array(
                'id'          => 206,
                'province_id' => 17,
                'name'        => '上饶',
                'status'      => 1,
            ),
            206 => array(
                'id'          => 207,
                'province_id' => 17,
                'name'        => '新余',
                'status'      => 1,
            ),
            207 => array(
                'id'          => 208,
                'province_id' => 17,
                'name'        => '宜春',
                'status'      => 1,
            ),
            208 => array(
                'id'          => 209,
                'province_id' => 17,
                'name'        => '鹰潭',
                'status'      => 1,
            ),
            209 => array(
                'id'          => 210,
                'province_id' => 18,
                'name'        => '沈阳',
                'status'      => 1,
            ),
            210 => array(
                'id'          => 211,
                'province_id' => 18,
                'name'        => '大连',
                'status'      => 1,
            ),
            211 => array(
                'id'          => 212,
                'province_id' => 18,
                'name'        => '鞍山',
                'status'      => 1,
            ),
            212 => array(
                'id'          => 213,
                'province_id' => 18,
                'name'        => '本溪',
                'status'      => 1,
            ),
            213 => array(
                'id'          => 214,
                'province_id' => 18,
                'name'        => '朝阳',
                'status'      => 1,
            ),
            214 => array(
                'id'          => 215,
                'province_id' => 18,
                'name'        => '丹东',
                'status'      => 1,
            ),
            215 => array(
                'id'          => 216,
                'province_id' => 18,
                'name'        => '抚顺',
                'status'      => 1,
            ),
            216 => array(
                'id'          => 217,
                'province_id' => 18,
                'name'        => '阜新',
                'status'      => 1,
            ),
            217 => array(
                'id'          => 218,
                'province_id' => 18,
                'name'        => '葫芦岛',
                'status'      => 1,
            ),
            218 => array(
                'id'          => 219,
                'province_id' => 18,
                'name'        => '锦州',
                'status'      => 1,
            ),
            219 => array(
                'id'          => 220,
                'province_id' => 18,
                'name'        => '辽阳',
                'status'      => 1,
            ),
            220 => array(
                'id'          => 221,
                'province_id' => 18,
                'name'        => '盘锦',
                'status'      => 1,
            ),
            221 => array(
                'id'          => 222,
                'province_id' => 18,
                'name'        => '铁岭',
                'status'      => 1,
            ),
            222 => array(
                'id'          => 223,
                'province_id' => 18,
                'name'        => '营口',
                'status'      => 1,
            ),
            223 => array(
                'id'          => 224,
                'province_id' => 19,
                'name'        => '呼和浩特',
                'status'      => 1,
            ),
            224 => array(
                'id'          => 225,
                'province_id' => 19,
                'name'        => '阿拉善盟',
                'status'      => 1,
            ),
            225 => array(
                'id'          => 226,
                'province_id' => 19,
                'name'        => '巴彦淖尔盟',
                'status'      => 1,
            ),
            226 => array(
                'id'          => 227,
                'province_id' => 19,
                'name'        => '包头',
                'status'      => 1,
            ),
            227 => array(
                'id'          => 228,
                'province_id' => 19,
                'name'        => '赤峰',
                'status'      => 1,
            ),
            228 => array(
                'id'          => 229,
                'province_id' => 19,
                'name'        => '鄂尔多斯',
                'status'      => 1,
            ),
            229 => array(
                'id'          => 230,
                'province_id' => 19,
                'name'        => '呼伦贝尔',
                'status'      => 1,
            ),
            230 => array(
                'id'          => 231,
                'province_id' => 19,
                'name'        => '通辽',
                'status'      => 1,
            ),
            231 => array(
                'id'          => 232,
                'province_id' => 19,
                'name'        => '乌海',
                'status'      => 1,
            ),
            232 => array(
                'id'          => 233,
                'province_id' => 19,
                'name'        => '乌兰察布市',
                'status'      => 1,
            ),
            233 => array(
                'id'          => 234,
                'province_id' => 19,
                'name'        => '锡林郭勒盟',
                'status'      => 1,
            ),
            234 => array(
                'id'          => 235,
                'province_id' => 19,
                'name'        => '兴安盟',
                'status'      => 1,
            ),
            235 => array(
                'id'          => 236,
                'province_id' => 20,
                'name'        => '银川',
                'status'      => 1,
            ),
            236 => array(
                'id'          => 237,
                'province_id' => 20,
                'name'        => '固原',
                'status'      => 1,
            ),
            237 => array(
                'id'          => 238,
                'province_id' => 20,
                'name'        => '石嘴山',
                'status'      => 1,
            ),
            238 => array(
                'id'          => 239,
                'province_id' => 20,
                'name'        => '吴忠',
                'status'      => 1,
            ),
            239 => array(
                'id'          => 240,
                'province_id' => 20,
                'name'        => '中卫',
                'status'      => 1,
            ),
            240 => array(
                'id'          => 241,
                'province_id' => 21,
                'name'        => '西宁',
                'status'      => 1,
            ),
            241 => array(
                'id'          => 242,
                'province_id' => 21,
                'name'        => '果洛',
                'status'      => 1,
            ),
            242 => array(
                'id'          => 243,
                'province_id' => 21,
                'name'        => '海北',
                'status'      => 1,
            ),
            243 => array(
                'id'          => 244,
                'province_id' => 21,
                'name'        => '海东',
                'status'      => 1,
            ),
            244 => array(
                'id'          => 245,
                'province_id' => 21,
                'name'        => '海南',
                'status'      => 1,
            ),
            245 => array(
                'id'          => 246,
                'province_id' => 21,
                'name'        => '海西',
                'status'      => 1,
            ),
            246 => array(
                'id'          => 247,
                'province_id' => 21,
                'name'        => '黄南',
                'status'      => 1,
            ),
            247 => array(
                'id'          => 248,
                'province_id' => 21,
                'name'        => '玉树',
                'status'      => 1,
            ),
            248 => array(
                'id'          => 249,
                'province_id' => 22,
                'name'        => '济南',
                'status'      => 1,
            ),
            249 => array(
                'id'          => 250,
                'province_id' => 22,
                'name'        => '青岛',
                'status'      => 1,
            ),
            250 => array(
                'id'          => 251,
                'province_id' => 22,
                'name'        => '滨州',
                'status'      => 1,
            ),
            251 => array(
                'id'          => 252,
                'province_id' => 22,
                'name'        => '德州',
                'status'      => 1,
            ),
            252 => array(
                'id'          => 253,
                'province_id' => 22,
                'name'        => '东营',
                'status'      => 1,
            ),
            253 => array(
                'id'          => 254,
                'province_id' => 22,
                'name'        => '菏泽',
                'status'      => 1,
            ),
            254 => array(
                'id'          => 255,
                'province_id' => 22,
                'name'        => '济宁',
                'status'      => 1,
            ),
            255 => array(
                'id'          => 256,
                'province_id' => 22,
                'name'        => '莱芜',
                'status'      => 1,
            ),
            256 => array(
                'id'          => 257,
                'province_id' => 22,
                'name'        => '聊城',
                'status'      => 1,
            ),
            257 => array(
                'id'          => 258,
                'province_id' => 22,
                'name'        => '临沂',
                'status'      => 1,
            ),
            258 => array(
                'id'          => 259,
                'province_id' => 22,
                'name'        => '日照',
                'status'      => 1,
            ),
            259 => array(
                'id'          => 260,
                'province_id' => 22,
                'name'        => '泰安',
                'status'      => 1,
            ),
            260 => array(
                'id'          => 261,
                'province_id' => 22,
                'name'        => '威海',
                'status'      => 1,
            ),
            261 => array(
                'id'          => 262,
                'province_id' => 22,
                'name'        => '潍坊',
                'status'      => 1,
            ),
            262 => array(
                'id'          => 263,
                'province_id' => 22,
                'name'        => '烟台',
                'status'      => 1,
            ),
            263 => array(
                'id'          => 264,
                'province_id' => 22,
                'name'        => '枣庄',
                'status'      => 1,
            ),
            264 => array(
                'id'          => 265,
                'province_id' => 22,
                'name'        => '淄博',
                'status'      => 1,
            ),
            265 => array(
                'id'          => 266,
                'province_id' => 23,
                'name'        => '太原',
                'status'      => 1,
            ),
            266 => array(
                'id'          => 267,
                'province_id' => 23,
                'name'        => '长治',
                'status'      => 1,
            ),
            267 => array(
                'id'          => 268,
                'province_id' => 23,
                'name'        => '大同',
                'status'      => 1,
            ),
            268 => array(
                'id'          => 269,
                'province_id' => 23,
                'name'        => '晋城',
                'status'      => 1,
            ),
            269 => array(
                'id'          => 270,
                'province_id' => 23,
                'name'        => '晋中',
                'status'      => 1,
            ),
            270 => array(
                'id'          => 271,
                'province_id' => 23,
                'name'        => '临汾',
                'status'      => 1,
            ),
            271 => array(
                'id'          => 272,
                'province_id' => 23,
                'name'        => '吕梁',
                'status'      => 1,
            ),
            272 => array(
                'id'          => 273,
                'province_id' => 23,
                'name'        => '朔州',
                'status'      => 1,
            ),
            273 => array(
                'id'          => 274,
                'province_id' => 23,
                'name'        => '忻州',
                'status'      => 1,
            ),
            274 => array(
                'id'          => 275,
                'province_id' => 23,
                'name'        => '阳泉',
                'status'      => 1,
            ),
            275 => array(
                'id'          => 276,
                'province_id' => 23,
                'name'        => '运城',
                'status'      => 1,
            ),
            276 => array(
                'id'          => 277,
                'province_id' => 24,
                'name'        => '西安',
                'status'      => 1,
            ),
            277 => array(
                'id'          => 278,
                'province_id' => 24,
                'name'        => '安康',
                'status'      => 1,
            ),
            278 => array(
                'id'          => 279,
                'province_id' => 24,
                'name'        => '宝鸡',
                'status'      => 1,
            ),
            279 => array(
                'id'          => 280,
                'province_id' => 24,
                'name'        => '汉中',
                'status'      => 1,
            ),
            280 => array(
                'id'          => 281,
                'province_id' => 24,
                'name'        => '商洛',
                'status'      => 1,
            ),
            281 => array(
                'id'          => 282,
                'province_id' => 24,
                'name'        => '铜川',
                'status'      => 1,
            ),
            282 => array(
                'id'          => 283,
                'province_id' => 24,
                'name'        => '渭南',
                'status'      => 1,
            ),
            283 => array(
                'id'          => 284,
                'province_id' => 24,
                'name'        => '咸阳',
                'status'      => 1,
            ),
            284 => array(
                'id'          => 285,
                'province_id' => 24,
                'name'        => '延安',
                'status'      => 1,
            ),
            285 => array(
                'id'          => 286,
                'province_id' => 24,
                'name'        => '榆林',
                'status'      => 1,
            ),
            286 => array(
                'id'          => 287,
                'province_id' => 25,
                'name'        => '上海',
                'status'      => 1,
            ),
            287 => array(
                'id'          => 288,
                'province_id' => 26,
                'name'        => '成都',
                'status'      => 1,
            ),
            288 => array(
                'id'          => 289,
                'province_id' => 26,
                'name'        => '绵阳',
                'status'      => 1,
            ),
            289 => array(
                'id'          => 290,
                'province_id' => 26,
                'name'        => '阿坝',
                'status'      => 1,
            ),
            290 => array(
                'id'          => 291,
                'province_id' => 26,
                'name'        => '巴中',
                'status'      => 1,
            ),
            291 => array(
                'id'          => 292,
                'province_id' => 26,
                'name'        => '达州',
                'status'      => 1,
            ),
            292 => array(
                'id'          => 293,
                'province_id' => 26,
                'name'        => '德阳',
                'status'      => 1,
            ),
            293 => array(
                'id'          => 294,
                'province_id' => 26,
                'name'        => '甘孜',
                'status'      => 1,
            ),
            294 => array(
                'id'          => 295,
                'province_id' => 26,
                'name'        => '广安',
                'status'      => 1,
            ),
            295 => array(
                'id'          => 296,
                'province_id' => 26,
                'name'        => '广元',
                'status'      => 1,
            ),
            296 => array(
                'id'          => 297,
                'province_id' => 26,
                'name'        => '乐山',
                'status'      => 1,
            ),
            297 => array(
                'id'          => 298,
                'province_id' => 26,
                'name'        => '凉山',
                'status'      => 1,
            ),
            298 => array(
                'id'          => 299,
                'province_id' => 26,
                'name'        => '眉山',
                'status'      => 1,
            ),
            299 => array(
                'id'          => 300,
                'province_id' => 26,
                'name'        => '南充',
                'status'      => 1,
            ),
            300 => array(
                'id'          => 301,
                'province_id' => 26,
                'name'        => '内江',
                'status'      => 1,
            ),
            301 => array(
                'id'          => 302,
                'province_id' => 26,
                'name'        => '攀枝花',
                'status'      => 1,
            ),
            302 => array(
                'id'          => 303,
                'province_id' => 26,
                'name'        => '遂宁',
                'status'      => 1,
            ),
            303 => array(
                'id'          => 304,
                'province_id' => 26,
                'name'        => '雅安',
                'status'      => 1,
            ),
            304 => array(
                'id'          => 305,
                'province_id' => 26,
                'name'        => '宜宾',
                'status'      => 1,
            ),
            305 => array(
                'id'          => 306,
                'province_id' => 26,
                'name'        => '资阳',
                'status'      => 1,
            ),
            306 => array(
                'id'          => 307,
                'province_id' => 26,
                'name'        => '自贡',
                'status'      => 1,
            ),
            307 => array(
                'id'          => 308,
                'province_id' => 26,
                'name'        => '泸州',
                'status'      => 1,
            ),
            308 => array(
                'id'          => 309,
                'province_id' => 27,
                'name'        => '天津',
                'status'      => 1,
            ),
            309 => array(
                'id'          => 310,
                'province_id' => 28,
                'name'        => '拉萨',
                'status'      => 1,
            ),
            310 => array(
                'id'          => 311,
                'province_id' => 28,
                'name'        => '阿里',
                'status'      => 1,
            ),
            311 => array(
                'id'          => 312,
                'province_id' => 28,
                'name'        => '昌都',
                'status'      => 1,
            ),
            312 => array(
                'id'          => 313,
                'province_id' => 28,
                'name'        => '林芝',
                'status'      => 1,
            ),
            313 => array(
                'id'          => 314,
                'province_id' => 28,
                'name'        => '那曲',
                'status'      => 1,
            ),
            314 => array(
                'id'          => 315,
                'province_id' => 28,
                'name'        => '日喀则',
                'status'      => 1,
            ),
            315 => array(
                'id'          => 316,
                'province_id' => 28,
                'name'        => '山南',
                'status'      => 1,
            ),
            316 => array(
                'id'          => 317,
                'province_id' => 29,
                'name'        => '乌鲁木齐',
                'status'      => 1,
            ),
            317 => array(
                'id'          => 318,
                'province_id' => 29,
                'name'        => '阿克苏',
                'status'      => 1,
            ),
            318 => array(
                'id'          => 319,
                'province_id' => 29,
                'name'        => '阿拉尔',
                'status'      => 1,
            ),
            319 => array(
                'id'          => 320,
                'province_id' => 29,
                'name'        => '巴音郭楞',
                'status'      => 1,
            ),
            320 => array(
                'id'          => 321,
                'province_id' => 29,
                'name'        => '博尔塔拉',
                'status'      => 1,
            ),
            321 => array(
                'id'          => 322,
                'province_id' => 29,
                'name'        => '昌吉',
                'status'      => 1,
            ),
            322 => array(
                'id'          => 323,
                'province_id' => 29,
                'name'        => '哈密',
                'status'      => 1,
            ),
            323 => array(
                'id'          => 324,
                'province_id' => 29,
                'name'        => '和田',
                'status'      => 1,
            ),
            324 => array(
                'id'          => 325,
                'province_id' => 29,
                'name'        => '喀什',
                'status'      => 1,
            ),
            325 => array(
                'id'          => 326,
                'province_id' => 29,
                'name'        => '克拉玛依',
                'status'      => 1,
            ),
            326 => array(
                'id'          => 327,
                'province_id' => 29,
                'name'        => '克孜勒苏',
                'status'      => 1,
            ),
            327 => array(
                'id'          => 328,
                'province_id' => 29,
                'name'        => '石河子',
                'status'      => 1,
            ),
            328 => array(
                'id'          => 329,
                'province_id' => 29,
                'name'        => '图木舒克',
                'status'      => 1,
            ),
            329 => array(
                'id'          => 330,
                'province_id' => 29,
                'name'        => '吐鲁番',
                'status'      => 1,
            ),
            330 => array(
                'id'          => 331,
                'province_id' => 29,
                'name'        => '五家渠',
                'status'      => 1,
            ),
            331 => array(
                'id'          => 332,
                'province_id' => 29,
                'name'        => '伊犁',
                'status'      => 1,
            ),
            332 => array(
                'id'          => 333,
                'province_id' => 30,
                'name'        => '昆明',
                'status'      => 1,
            ),
            333 => array(
                'id'          => 334,
                'province_id' => 30,
                'name'        => '怒江',
                'status'      => 1,
            ),
            334 => array(
                'id'          => 335,
                'province_id' => 30,
                'name'        => '普洱',
                'status'      => 1,
            ),
            335 => array(
                'id'          => 336,
                'province_id' => 30,
                'name'        => '丽江',
                'status'      => 1,
            ),
            336 => array(
                'id'          => 337,
                'province_id' => 30,
                'name'        => '保山',
                'status'      => 1,
            ),
            337 => array(
                'id'          => 338,
                'province_id' => 30,
                'name'        => '楚雄',
                'status'      => 1,
            ),
            338 => array(
                'id'          => 339,
                'province_id' => 30,
                'name'        => '大理',
                'status'      => 1,
            ),
            339 => array(
                'id'          => 340,
                'province_id' => 30,
                'name'        => '德宏',
                'status'      => 1,
            ),
            340 => array(
                'id'          => 341,
                'province_id' => 30,
                'name'        => '迪庆',
                'status'      => 1,
            ),
            341 => array(
                'id'          => 342,
                'province_id' => 30,
                'name'        => '红河',
                'status'      => 1,
            ),
            342 => array(
                'id'          => 343,
                'province_id' => 30,
                'name'        => '临沧',
                'status'      => 1,
            ),
            343 => array(
                'id'          => 344,
                'province_id' => 30,
                'name'        => '曲靖',
                'status'      => 1,
            ),
            344 => array(
                'id'          => 345,
                'province_id' => 30,
                'name'        => '文山',
                'status'      => 1,
            ),
            345 => array(
                'id'          => 346,
                'province_id' => 30,
                'name'        => '西双版纳',
                'status'      => 1,
            ),
            346 => array(
                'id'          => 347,
                'province_id' => 30,
                'name'        => '玉溪',
                'status'      => 1,
            ),
            347 => array(
                'id'          => 348,
                'province_id' => 30,
                'name'        => '昭通',
                'status'      => 1,
            ),
            348 => array(
                'id'          => 349,
                'province_id' => 31,
                'name'        => '杭州',
                'status'      => 1,
            ),
            349 => array(
                'id'          => 350,
                'province_id' => 31,
                'name'        => '湖州',
                'status'      => 1,
            ),
            350 => array(
                'id'          => 351,
                'province_id' => 31,
                'name'        => '嘉兴',
                'status'      => 1,
            ),
            351 => array(
                'id'          => 352,
                'province_id' => 31,
                'name'        => '金华',
                'status'      => 1,
            ),
            352 => array(
                'id'          => 353,
                'province_id' => 31,
                'name'        => '丽水',
                'status'      => 1,
            ),
            353 => array(
                'id'          => 354,
                'province_id' => 31,
                'name'        => '宁波',
                'status'      => 1,
            ),
            354 => array(
                'id'          => 355,
                'province_id' => 31,
                'name'        => '绍兴',
                'status'      => 1,
            ),
            355 => array(
                'id'          => 356,
                'province_id' => 31,
                'name'        => '台州',
                'status'      => 1,
            ),
            356 => array(
                'id'          => 357,
                'province_id' => 31,
                'name'        => '温州',
                'status'      => 1,
            ),
            357 => array(
                'id'          => 358,
                'province_id' => 31,
                'name'        => '舟山',
                'status'      => 1,
            ),
            358 => array(
                'id'          => 359,
                'province_id' => 31,
                'name'        => '衢州',
                'status'      => 1,
            ),
            359 => array(
                'id'          => 360,
                'province_id' => 32,
                'name'        => '重庆',
                'status'      => 1,
            ),
            360 => array(
                'id'          => 361,
                'province_id' => 33,
                'name'        => '香港',
                'status'      => 1,
            ),
            361 => array(
                'id'          => 362,
                'province_id' => 34,
                'name'        => '澳门',
                'status'      => 1,
            ),
            362 => array(
                'id'          => 363,
                'province_id' => 35,
                'name'        => '台湾',
                'status'      => 1,
            ),
        ));

    }
}
